### ISSUE TITLE
Xkcd 1732 problems

### ISSUE THREAD

**Issue by rugk** [tom-anders/Easy_xkcd#101]
The current - maybe too big - comic causes two issues:
1. It let's easy xkcd regularly crash in the background (I think this is caused by the widget)
2. Even when starting the app manually the comic is not displayed

**Comment by T-Rex96** [comment]
The image is probably too large for your device, see this issue: https://github.com/T-Rex96/Easy_xkcd/issues/55

**Comment by rugk** [comment]
Yes, I cannot see 1227 either.
I am on CM13 (Android 6).

So, but what can you do about it? Can't you maybe scale it down?
Or at least prevent the crashes?

**Comment by EmmanuelMess** [comment]
Isn't this app using Glide? It should be rather easy to resize images so that the device can show them.

**Comment by tom-anders** [comment]
This was fixed with 9f102615 (as @EmmanuelMess suggested the app now uses a custom AppGlideModule that resizes huge images)
