### ISSUE TITLE
Open displayed image when opening app from widget

### ISSUE THREAD

**Issue by rugk** [tom-anders/Easy_xkcd#106]
STR: tap on the widget to open the app

What happens: app starts as usual (with the last displayed comic in the app) and e.g. shows a "there are new comics" bar at the bottom

What should happen: start app with the comic displayed in the widget and suppress "new comics" notification when this is the latest comic

**Comment by tom-anders** [comment]
Widget logic was rewritten in 8.0, this should work now.
