### ISSUE TITLE
Share the image and title

### ISSUE THREAD

**Issue by Zykino** [tom-anders/Easy_xkcd#111]
When sharing an XKCD comic the person I send it too should be able to have the "full experience" so a share function like Twidere does would be perfect:
- Image
- Title (comment of the author)
- Link (to use his own app on it)

Maybe we would also include the comic title.

**Comment by the-cybersapien** [comment]
Is anyone working on this? I'd really like to try and do this!

**Comment by T-Rex96** [comment]
Go ahead! I'm really busy with University stuff at the moment, so I don't really have time to work on the app myself

**Comment by mueller-ma** [comment]
With https://github.com/tom-anders/Easy_xkcd/pull/153 image shares include title, alt text (if enabled) and link (if enabled).
