### ISSUE TITLE
No comics are shown when blocked via firewall

### ISSUE THREAD

**Issue by mueller-ma** [tom-anders/Easy_xkcd#114]
I use afwall+ to block easyxkcd from using cellular internet. Wifi is allowed and i have enabled offline mode.
When i am not on wifi easyxkcd searches for new images and as result no comics are shown

**Comment by tom-anders** [comment]
There's an option to update offline mode only on Wifi, doesn't that one work?

**Comment by mueller-ma** [comment]
I don't use that Firewall anymore, so I'm going to close this issue.
