### ISSUE TITLE
WebView scroll position lost after device rotation

### ISSUE THREAD

**Issue by calbee633810** [tom-anders/Easy_xkcd#128]
Steps to reproduce:
1. Open What if?
2. Click any article in the list
3. Scroll the article
4. Rotate device

Scroll position should persist after rotation, however, it get lost. It's annoying because user has to manually scroll to the expected position every time screen orientation change.

![screen shot 2018-04-12 at 11 19 56 pm](https://user-images.githubusercontent.com/38213896/38686917-10a0cc3e-3ea8-11e8-9238-be846e2baa36.png)
Screenshot before rotation

![screen shot 2018-04-12 at 11 20 07 pm](https://user-images.githubusercontent.com/38213896/38686923-17fb8fc8-3ea8-11e8-9421-fe1994b4b03a.png)
Screenshot after rotation.

**Comment by tom-anders** [comment]
Fixed, see #242
