### ISSUE TITLE
Emojis in alt text of comic do not display correctly (Comic #2131)

### ISSUE THREAD

**Issue by afritsch** [tom-anders/Easy_xkcd#148]
Link here: https://xkcd.com/2131/
This Emoji: 🤼 (People Wrestling)

I would assume all emojis in the alt text are broken. There might be future occurences of emojis in the alt text, so I would say it's a sensible thing to fix.

Device: Xiaomi Mi Mix 2S, Android 9, Stock Rom

![Screenshot_2019-04-01-21-57-09-075_de tap easy_xkcd](https://user-images.githubusercontent.com/497652/55355702-56a00c80-54c9-11e9-937f-61519113e106.png)

**Comment by T-Rex96** [comment]
Well, the comic's alt text has actually changed now, but I'll leave this issue open if someone wants to try and fix this. It's apparently not as trivial as it sounds (at least according to my quick stackoverflow search)

**Comment by theck13** [comment]
Adding `Html.fromHtml` to the `tvAlt.setText(comic.getAltText())` call in `ComicFragment` works for me.  I created a pull request, https://github.com/tom-anders/Easy_xkcd/pull/150, for review.

**Comment by tom-anders** [comment]
Well that was quick =)
