### ISSUE TITLE
F-droid build requires Android 5

### ISSUE THREAD

**Issue by hackerb9** [tom-anders/Easy_xkcd#151]
The old versions on F-droid used to work fine on my Amazon FireOS device (which is a fork from Android 4). When I updated today, I received installation errors. I tried uninstalling, but then found I couldn't reinstall. Only versions >7.3 are available and they all require Android 5.

Could you please rebuild for Android 4 or better? 

If that is not possible, please re-upload the old versions, which had been working fine.

Thanks!

**Comment by tom-anders** [comment]
Unfortunately supporting Android 4 is not possible anymore, but you download the old version here https://f-droid.org/en/packages/de.tap.easy_xkcd/
