### ISSUE TITLE
Unexpected behaviours after a screen orientation change (reported by activity)

### ISSUE THREAD

**Issue by datalossdetector** [tom-anders/Easy_xkcd#163]
I developed an automatic test case generation tool and it detected these problems in your app.
I would like to know if you consider them as failures and, if not, why. Thanks for your collaboration.

1) In WhatIfActivity, when I change the orientation of the device screen, the Dialog widget reported in the screenshot below disappears.
![2019-07-13 02-21-33_before](https://user-images.githubusercontent.com/53469180/62131245-13b93e80-b2db-11e9-8ceb-4f66a3f10775.png)
![2019-07-13 02-21-33_after](https://user-images.githubusercontent.com/53469180/62131242-13b93e80-b2db-11e9-805b-937d6a36456f.png)

2) NestedSettingsActivity, when I change the orientation of the device screen, changes its state. Below there are three different examples: the screenshots were taken before and after the screen orientation change and they are paired (before, after), (before, after) ...

**--- first case ---**

The clock dialog disappears. 

![2019-07-13 01-47-10_before](https://user-images.githubusercontent.com/53469180/62131076-bfae5a00-b2da-11e9-9870-edb6bf3a2d63.png)
![2019-07-13 01-47-10_after](https://user-images.githubusercontent.com/53469180/62131081-c210b400-b2da-11e9-9b85-64ba867ed7ee.png)

**--- second case ---**

From "night options" goes to "settings".

![2019-07-13 01-29-40_before](https://user-images.githubusercontent.com/53469180/62131088-c3da7780-b2da-11e9-910e-314c436a1ea3.png)
![2019-07-13 01-29-40_after](https://user-images.githubusercontent.com/53469180/62131092-c63cd180-b2da-11e9-8b37-eedf402cf9bd.png)

**--- third case ---**

From "Appearance" it goes to "Settings".

![2019-07-13 00-57-36_before](https://user-images.githubusercontent.com/53469180/62131098-c89f2b80-b2da-11e9-8c7e-ae64cf58ff89.png)
![2019-07-13 00-57-36_after](https://user-images.githubusercontent.com/53469180/62131104-cb018580-b2da-11e9-9a61-c923e89032dc.png)

3) MainActivity, when I change the orientation of the device screen, changes its state. Below there are five different examples: the screenshots were taken before and after the screen orientation change and they are paired (before, after), (before, after) ...

**--- first case ---**

The displayed comic disappears and it returns back to the list of comics.

![2019-07-13 00-50-26_before](https://user-images.githubusercontent.com/53469180/62130731-f0da5a80-b2d9-11e9-993f-ec742eae8b43.png)
![2019-07-13 00-50-26_after](https://user-images.githubusercontent.com/53469180/62130730-f0da5a80-b2d9-11e9-9790-dcbcdaee482e.png)

**--- second case ---**

The content inside the search bar disappears and the dialog changes its options.

![2019-07-13 02-14-40_before](https://user-images.githubusercontent.com/53469180/62130755-fcc61c80-b2d9-11e9-9025-2ed532f8d234.png)
![2019-07-13 02-14-40_after](https://user-images.githubusercontent.com/53469180/62130762-ffc10d00-b2d9-11e9-9d36-056966b1e9d0.png)

**--- third case ---**

The dialog disappears from the screen.

![2019-07-13 02-28-22_before](https://user-images.githubusercontent.com/53469180/62130776-03ed2a80-b2da-11e9-8a29-d7c7136caab6.png)
![2019-07-13 02-28-22_after](https://user-images.githubusercontent.com/53469180/62130779-0780b180-b2da-11e9-965e-a71a3139abbb.png)

**--- fourth case---**

The content inside the search bar disappears.

![2019-07-13 04-40-40_before](https://user-images.githubusercontent.com/53469180/62130784-0a7ba200-b2da-11e9-9a25-5e8893a7cb8b.png)
![2019-07-13 04-40-40_after](https://user-images.githubusercontent.com/53469180/62130788-0cddfc00-b2da-11e9-85d3-a032dd1b6169.png)

**--- fifth case ---**

The navigation drawer disappears.

![2019-07-15 23-15-40_before](https://user-images.githubusercontent.com/53469180/62130796-0ea7bf80-b2da-11e9-837f-7cda9184df95.png)
![2019-07-15 23-15-40_after](https://user-images.githubusercontent.com/53469180/62130802-110a1980-b2da-11e9-9ece-d0c0e85933bb.png)

**Comment by tom-anders** [comment]
Yeah all of those seem like bugs, thanks for that.

**Comment by dlicse1** [comment]
Thank you very much!

**Comment by tom-anders** [comment]
Should be either fixed or obsolete in 8.0
