### ISSUE TITLE
Misuse of AsyncTask

### ISSUE THREAD

**Issue by pangeneral** [tom-anders/Easy_xkcd#164]
According to our research, there are misuses about the following AsyncTask classes:
1. `de.tap.easy_xkcd.fragments.NestedPreferenceFragment.deleteComicsTask`
2. `de.tap.easy_xkcd.fragments.NestedPreferenceFragment.deleteArticlesTask`

The problems is:
The instance of these AsyncTask classes are annoymous object. For instance, `new deleteArticlesTask().execute()`). These objects can not be cancelled before the Activity is destroyed, which can lead to the wrong invocation of `onPostExecute()` if the Activity has been destroyed.

I think we can make following change to fix the misuse problem:
Add AsyncTask field in `NestedPreferenceFragment` for these AsyncTask object and invoke `cancel()` in the `onDestroy()` method if the AsyncTask field is not null.

These are my suggestions above, thank you.

**Comment by tom-anders** [comment]
Sounds right, feel free to make a pull request :)

**Comment by tom-anders** [comment]
8.0 does not use async task anymore
