### ISSUE TITLE
Comic 2202 doesn't show up

### ISSUE THREAD

**Issue by wolkenschieber** [tom-anders/Easy_xkcd#169]
When opening comic 2202 - _Earth-Like Exoplanet_, the loading animation is shown, but actual comic never appears.

**Comment by tom-anders** [comment]
Are you on F-droid? This is already fixed in 7.3.5, it usually takes a while for the update to show up on f-droid as well

**Comment by wolkenschieber** [comment]
Yes, I'm on fdroid's 7.3.4.
