### ISSUE TITLE
Switching nighttime theme twice moves you to last comic

### ISSUE THREAD

**Issue by EmmanuelMess** [tom-anders/Easy_xkcd#170]

**Comment by tom-anders** [comment]
Where exactly does that happen? Can you share the steps to reproduce this?

**Comment by EmmanuelMess** [comment]
1. Go to any comic that is not the last
2. Select "night theme" in the overflow menu in appbar
3. Select again "night theme" in the overflow menu in appbar
4. You are at the last comic

**Comment by tom-anders** [comment]
Ah right, I didn't read the "twice", sorry!

**Comment by tom-anders** [comment]
Fixed in 8.0
