### ISSUE TITLE
Ttitle text HTML is interpreted (see comic 1965)

### ISSUE THREAD

**Issue by I-Al-Istannen** [tom-anders/Easy_xkcd#176]
## Problem

The title text for comics seems to parse and display HTML code. It hopefully sanitizes it first, but it should *probably* still not do that.

## How to reproduce
Go to comic `1965: Background Apps` and long tab. You will see something like:
![Screenshot_20191006-124919_Easy_xkcd](https://user-images.githubusercontent.com/20284688/66704346-9c585000-ed0a-11e9-8941-c236fb377568.png)

The real alt text is: 
> `My plane banner company gets business by flying around with a banner showing a <div> tag, waiting for a web developer to get frustrated enough to order a matching </div>.`

As you can see the `div` is gone from the text but apparently (there is a gap) evaluated.

**Comment by PeterHindes** [comment]
i think its getting cleared, not interpreted. I can fix it if you can find where the parsing happens. The app is kind of a maze of quick fixes.

**Comment by tom-anders** [comment]
Take a look at [RealmComic class](https://github.com/tom-anders/Easy_xkcd/blob/master/app/src/main/java/de/tap/easy_xkcd/database/RealmComic.java)

**Comment by PeterHindes** [comment]
I got about that far, but i got confused. Could you walk me through the process of where the data is pulled from.

**Comment by Shrubhog** [comment]
It's probably more likely that it is not Easy_xkcd that is interpreting the tag but the text box that's using `getAltText()`. It may help to escape the tags- I'll see if I can get a workspace running and see if that helps.

**Comment by Shrubhog** [comment]
I'm a bit confused why `Html.fromHtml()` is present at [line 216 in ComicFragment,](https://github.com/tom-anders/Easy_xkcd/blob/ab691dbcafb2937044115eb29677a95a94553f89/app/src/main/java/de/tap/easy_xkcd/fragments/comics/ComicFragment.java#L216) but I'll leave it alone.

Simply wrapping the call to `getAltText()` with `Html.escapeHtml()` did the trick; I'll send in a PR sometime soon.
![Screenshot_20200925-142126_Easy xkcd](https://user-images.githubusercontent.com/37482938/94307550-a3d43180-ff3a-11ea-87ec-e41ab7a8b03c.jpg)
