### ISSUE TITLE
The "overview" button and view is not behaving correctly

### ISSUE THREAD

**Issue by 0211beno** [tom-anders/Easy_xkcd#178]
1. Pressing the _Comic Overview_ makes the comic index number disappear and only _Comics_ remains.
2. Pressing the _Comic Overview_ an additional time makes the overview mode show up but the list is incomplete. Comics 1-339 appear, then a jump to 2220 where it continues to 2241 where it missing a few in between.

I tried to uninstall the app in an attempt to fix the issue but I can seem to make a complete uninstall. My favorites still remain and the bug persists.

**Comment by SebiderSushi** [comment]
I can also complain about the need of pressing "Comic Overview" twice.

As for the missing entries: Sounds as if you've got "Hide read comics" ticked in the context menu on the Overview screen.

**Comment by tom-anders** [comment]
Should be fixed in the beta and upcoming 8.0 release

**Comment by SebiderSushi** [comment]
Thanks! Works as expected.
