### ISSUE TITLE
Suggestion for improving bitmap loading

### ISSUE THREAD

**Issue by cataloque** [tom-anders/Easy_xkcd#181]
Dear developers,
When loading an image, Google suggests us to resize the image before decoding them, so as to save memory resource and avoid OutOfMemory exception：
" To avoid java.lang.OutOfMemory exceptions, check the dimensions of a bitmap before decoding it, unless you absolutely trust the source to provide you with predictably sized image data that comfortably fits within the available memory "

By analysis this app,I founded that in the following method:
de.tap.easy_xkcd.database.RealmComic: android.graphics.Bitmap getOfflineBitmap(int,android.content.Context,de.tap.easy_xkcd.utils.PrefHelper),using decodeResource() to create bitmap,and resizing correctly.

However, in the code below, image is decoded directly without resizing:
de.tap.easy_xkcd.Activities.SearchResultsActivity$RVAdapter

I am curious about why this method do not resize image.if the imagees are large,that would  affect  the performance of Easy xkcd.Because bitmap is very memory consuming, maybe we should resize the images before decoding them, which can reduce memory overhead and help make app more smooth in user interaction.

Thanks.

**Comment by tom-anders** [comment]
version 8.0 now just passes the URI to Glide instead of decoding it beforehand.
