### ISSUE TITLE
Missing, shifted and squashed transcripts

### ISSUE THREAD

**Issue by SebiderSushi** [tom-anders/Easy_xkcd#183]
At least Comics 1609, 1610, 1650, 1651, 1665 and 1666 don't show a transcript. Instead, their transcripts get shifted to the next "free" comic, and as a result, some go missing, i.e:

| Comic number | Associated transcript |
|-|-|
| 1608 | 1608 |
| 1609 | none |
| 1610 | none |
| 1611 | 1609 |
| 1612 | 1610 |
| .... | ... |
| 1649 | 1647 |
| 1650 | none |
| 1651 | none |
| 1652 | 1650 |
| 1653 | 1651 |
| 1654 | 1652 |
| ... | ... |
| 1672 | 1669 |
| 1673 | 1670 |
| 1674 | 1671 |
| 1675 | "no transcripts after 1674" |

**Comment by JonnyTech** [comment]
I cannot confirm that, all good for me. Can you try wiping app data then checking again.

**Comment by SebiderSushi** [comment]
Hm, i can reproduce it on a Nexus 4, Lineage for microG 15.1, Easy xkcd version 7.3.6 from F-Droid.
- Uninstall, then reinstall app
- Launch, wait for "Updating database..."
- Tap "Search", type "1674", press enter
- Tap "more", tap "View Transcript"
=> Shows transcript of comic 1671

**Comment by JonnyTech** [comment]
Hmm, I found blank transcripts with 1672 and 1673, but no incorrect ones, and not the same blank ones as you. Every comic after 1674 displays the correct message about not having a transcript.
![1675](https://user-images.githubusercontent.com/3584732/76820839-29e12400-6804-11ea-839f-aa526f129ffd.jpg)

**Comment by SebiderSushi** [comment]
Did also wipe your data to force a full database refresh?

**Comment by tom-anders** [comment]
This is a known issue with the xkcd API: https://www.explainxkcd.com/wiki/index.php/Transcript_on_xkcd

version 8.0 now just ignores the xkcd API for transcripts above comic 1608 and uses explainxkcd.com instead for fetching them.

**Comment by SebiderSushi** [comment]
Thank you. Version 8.0.4 works perfectly now.
