### ISSUE TITLE
"Coronavirus Research" (2281) loading never completes

### ISSUE THREAD

**Issue by aaribaud** [tom-anders/Easy_xkcd#186]
Version 7.3.6 from F-Droid
In the comic list, comic "Coronavirus Research" (2281) shows the green spinner without ever loading.
Comic can be "opened", showing the same spinner.
Long press shows the Alt Text.

**Comment by tom-anders** [comment]
Already fixed in 7.3.7, should be coming to F-Droid in the next days, see https://github.com/tom-anders/Easy_xkcd/issues/187 

Sorry!

**Comment by tom-anders** [comment]
7.3.7 is on F-Droid now -> Closed
