### ISSUE TITLE
Create new release for F-Droid

### ISSUE THREAD

**Issue by Namnodorel** [tom-anders/Easy_xkcd#187]
The version of the app is almost half a year old, while the latest version is already on the Play Store. There should be a new release to keep both in sync.

btw: thank you for your work! easy XKCD is a great app to view the comic locally, and has been a good companion app for quite some time!

**Comment by tom-anders** [comment]
Oh, I forgot to push the commit that bumps the version, sorry for that! Should be picked up by F-Droid in the next few days hopefully
