### ISSUE TITLE
No images in "What if"-articles in offline mode

### ISSUE THREAD

**Issue by keikiki** [tom-anders/Easy_xkcd#190]
Hi,
first I'd like to thank you very much for programming this great app --- I really love it! Then I'd like to report you two issues that I have with the images in the "What if"-offline articles. Affected is the F-Droid version 7.3.7.

1. None of the images will be downloaded automatically, so no image will appear in an offline article.
2. Manually downloaded images have to be renamed in order to get displayed. Let's take article no.157 "Earth-Moon Fire Pole" as an example. The first image has to be renamed from "grav.png" to "1.png", the second image has to be renamed from "break.png" to "2.png", and so on. If you do so, everything works find. But the way to get there, is not very practical.

Are these issues known? If so, can they possibly be fixed in the next release, please?

Best regards,

keikiki

**Comment by tom-anders** [comment]
Should be fixed in 7.3.8, let me know if it worked for you! (You'll have to disable and the enable offline mode again for what-if)

**Comment by keikiki** [comment]
Great! Now it works. Thanks a lot.
