### ISSUE TITLE
No tests

### ISSUE THREAD

**Issue by ismail-s** [tom-anders/Easy_xkcd#20]
Well, OK, there is one default test but that's it. It would be good to have a nice test suite that can then be run on travis

**Comment by T-Rex96** [comment]
I'm not rally familar with that, can you expand on how that would benefit the app?

**Comment by ismail-s** [comment]
See stuff like http://stackoverflow.com/questions/67299/is-unit-testing-worth-the-effort .

From an open-source project POV, it means other people can make changes to code, and there is more certainty their changes don't mess stuff up. although tbh atm this project doesn't exactly have loads of contributors.

**Comment by tom-anders** [comment]
There are now small number of unit and regression tests, so I guess this issue can finally be closed now :) Of course I'm planning to add even more tests in the future.
