### ISSUE TITLE
Color navigation bar based on day/night theme

### ISSUE THREAD

**Issue by mueller-ma** [tom-anders/Easy_xkcd#201]
Currently the app has a preference to color the [navigation bar](https://material.io/design/platform-guidance/android-bars.html#android-navigation-bar) based on the primary color. IMO it's better to color the navigation bar unconditionally based on the background: white in the day theme (if the api supports a light nav bar) or dark grey in the night theme.
Google apps also do it this way.

@tom-anders With your ok, I'd start working on this.

**Comment by tom-anders** [comment]
Go for it!

Btw, I really appreciate all your recent work on the app :) 

The app probably needs a general design overhaul to adapt to the new guidelines. I also thought about switching from the navigation drawer to a bottom bar navigation, for example

**Comment by tom-anders** [comment]
@mueller-ma So recently I've been experimenting a bit with switching to [Bottom Navigation](https://material.io/components/bottom-navigation). Currently it looks a bit weird with the navigation bar color:

![image](https://user-images.githubusercontent.com/13141438/121248546-d8f39a80-c8a3-11eb-9af3-5c8bfe327d51.png)

Here's how it would look when the nav bar is color accordingly again:

![image](https://user-images.githubusercontent.com/13141438/121248601-e90b7a00-c8a3-11eb-8f16-70a4d868dc02.png)

Which looks a lot better IMO. What do you think?

**Comment by mueller-ma** [comment]
On material.io there's only a single screenshot of a bottom bar with device buttons below: https://material.io/components/bottom-navigation#behavior
In that screenshot the bar has just the default black. IMO the primaryDark looks better here.

**Comment by tom-anders** [comment]
Agreed. Primary Dark also looks nice since it also is the color of the status bar, creating nice symmetry.

**Comment by tom-anders** [comment]
Gonna close this once bottom navigation is merged with the according changes
