### ISSUE TITLE
Update icons

### ISSUE THREAD

**Issue by mueller-ma** [tom-anders/Easy_xkcd#207]
I suggest to update most of the icons in the app. I currently see three issues with them:
1. Some of the usual icons (search, favorite, etc.) are in the mipmap folders: https://github.com/tom-anders/Easy_xkcd/blob/master/app/src/main/res/mipmap-xhdpi/ic_nav_feedback.png. These folders should only be used for launcher icons: https://stackoverflow.com/a/24066445/13139982
2. They're PNG, but could/should be SVG
3. Some of them don't have the "default" name, that is used by Google, e.g. https://raw.githubusercontent.com/tom-anders/Easy_xkcd/master/app/src/main/res/drawable-xxhdpi/ic_whatif_next.png. IMO this makes it hard for new contributors to know the icon just from reading the icon name. `ic_baseline_keyboard_arrow_right` is probably better known across Android devs.

[Outline icons ](https://material.io/resources/icons/?style=outline)show up in many apps recently. @tom-anders Anything against moving to outline icons in this app as well?

**Comment by tom-anders** [comment]
For the outline icons I'd be interested in a before-after comparison

**Comment by mueller-ma** [comment]
I can start with the comic browser and open a draft PR then. What about point three in my first comment?

**Comment by tom-anders** [comment]
1) and 2) approved :)
3) I see your point, you can change this if you want

**Comment by mueller-ma** [comment]
I started with this in #208. After your ok, I update the remaining icons.

**Comment by mueller-ma** [comment]
Can you reopen this issue? A few icons haven't been replaced by my PR.
