### ISSUE TITLE
Possibility to export & import (favorites)?

### ISSUE THREAD

**Issue by rugk** [tom-anders/Easy_xkcd#231]
https://github.com/tom-anders/Easy_xkcd/issues/67 (/cc @acropup) seems to indicate there is (or was?) some kind of possibility to export the

I've switched my phone, but want to keep these _essential important bits of information_ from this app, i.e. my favorites.

I've searched the settings, but could not find any settings related to this…

**Comment by acropup** [comment]
Hi @rugk, try this:

Within the app, tap the main menu in the top left corner.
Tap Favorites.
Tap the three dots menu in the top right corner.
Tap "Export/Import Favorites" and then "Export".
I recommend emailing the exported file to yourself for backup, and for you to import on your new phone.

**Comment by tom-anders** [comment]
Thanks for the help, @acropup :)

**Comment by rugk** [comment]
Oh yes thanks, I'm stupid.
