### ISSUE TITLE
Import favs when no favorites are set

### ISSUE THREAD

**Issue by rugk** [tom-anders/Easy_xkcd#236]
After having https://github.com/tom-anders/Easy_xkcd/issues/231 answered I have a little problem:

You cannot access the "import favorites" menu when you have no favorites set, as it returns you to the main menu and says "you have no favorites".

For importing favorites, this is quite a deal-breaker… :stuck_out_tongue_winking_eye: :upside_down_face: 

Of course as a workaround you can fav one, import and unfav the one again, but this is inconvenient. :stuck_out_tongue_winking_eye:

**Comment by tom-anders** [comment]
Works in the beta now (and upcoming 8.0 release)

**Comment by rugk** [comment]
Yaay thanks a lot! :tada:
