### ISSUE TITLE
Article scrolls to top after device rotation

### ISSUE THREAD

**Issue by geniuslittleteddy** [tom-anders/Easy_xkcd#242]
Reading position gets lost after device rotation so that I have to manually scroll to the position I read before.

![Screen Shot 2020-08-17 at 10 11 21 PM](https://user-images.githubusercontent.com/67744580/90405708-b905a700-e0d6-11ea-93dd-9ca020082307.png)
![Screen Shot 2020-08-17 at 10 11 31 PM](https://user-images.githubusercontent.com/67744580/90405710-ba36d400-e0d6-11ea-9d80-798ddc101761.png)

**Comment by Shrubhog** [comment]
I have attempted to fix this using the `StateRestorationPolicy` introduced in the alpha versions of the RecyclerView library, but I have had no success; the WebView inside the WhatIf Activity appears to refresh on device rotation. I'll check to see whether it's possible to cache the state of the WebView specifically with a hacky method.
