### ISSUE TITLE
Can't finish updating database normally

### ISSUE THREAD

**Issue by Markmsq** [tom-anders/Easy_xkcd#249]
When I open the app for the first time, it started to updating database normally. But when the number hit 99/100, it didn't continue. And after I check the network, I found it really finish but just need to wait a long time to go on. Moreover, when I enable the offline mode, it can never finish updating again. So I just have half a day to use it. Otherwise, the short time of using this is perfect, so I want to use it again.

Some detail:  Android 9; I check both the storage and network usage to ensure it finished; I even use a VPN to try.

**Comment by tom-anders** [comment]
Should be fixed in the beta and the upcoming 8.0 release, which download comic data dynamically in the background
