### ISSUE TITLE
App crashes opening new comics

### ISSUE THREAD

**Issue by sophie-kuehn** [tom-anders/Easy_xkcd#250]
The last working comic is Blair Witch. Android Version is 8, Oreo.

APP_VERSION_NAME=7.3.9

STACK_TRACE=java.lang.RuntimeException: Canvas: trying to draw too large(134117388bytes) bitmap.

at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)

at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97)

at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)

at android.widget.ImageView.onDraw(ImageView.java:1367)

at android.view.View.draw(View.java:20373)

at android.view.View.updateDisplayListIfDirty(View.java:19318)

at android.view.View.draw(View.java:20096)

at android.view.ViewGroup.drawChild(ViewGroup.java:4421)

at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)

at android.view.View.updateDisplayListIfDirty(View.java:19309)

at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)

at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)

at android.view.View.updateDisplayListIfDirty(View.java:19277)

at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)

at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)

at android.view.View.updateDisplayListIfDirty(View.java:19277)

at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)

at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)

at android.view.View.updateDisplayListIfDirty(View.java:19277)

at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)

at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)

at android.view.View.updateDisplayListIfDirty(View.java:19277)

at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)

at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)

at android.view.View.updateDisplayListIfDirty(View.java:19277)

at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)

at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)

at android.view.View.updateDisplayListIfDirty(View.java:19277)

at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)

at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)

at android.view.View.updateDisplayListIfDirty(View.java:19277)

at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)

at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)

at android.view.View.updateDisplayListIfDirty(View.java:19277)

at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)

at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)

at android.view.View.updateDisplayListIfDirty(View.java:19277)

at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)

at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)

at android.view.View.updateDisplayListIfDirty(View.java:19277)

at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)

at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)

at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:800)

at android.view.ViewRootImpl.draw(ViewRootImpl.java:3496)

at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3283)

at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2818)

at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1780)

at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7827)

at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)

at android.view.Choreographer.doCallbacks(Choreographer.java:723)

at android.view.Choreographer.doFrame(Choreographer.java:658)

at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)

at android.os.Handler.handleCallback(Handler.java:789)

at android.os.Handler.dispatchMessage(Handler.java:98)

at android.os.Looper.loop(Looper.java:164)

at android.app.ActivityThread.main(ActivityThread.java:6944)

at java.lang.reflect.Method.invoke(Native Method)

at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)

at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

SHARED_PREFERENCES=default.pref_alt_style=0

default.pref_navbar=true

default.transcripts_fixed=true

default.pref_zoom_scroll=true

default.pref_custom_tabs=true

default.disable_nav_drawer_swipe=false

default.pref_offline=false

default.pref_mobile=false

default.pref_share=false

default.pref_alt_options=[pref_show_alt]

default.widget_comicNumber=true

default.pref_include_link=false

default.pref_hide_donate=false

default.pref_fullscreen_enabled=true

default.acra.legacyAlreadyConvertedTo4.8.0=true

default.pref_notifications=0

default.widget_alt=false

default.pref_nav_swipe=false

default.pref_doubletap=false

default.pref_offline_whatif=false

default.pref_alt_activation=1

default.cache_fixed_7.3.3=true

default.pref_overview_default=false

default.pref_zoom=default

default.pref_random=[pref_random_whatif]

default.cache_fixed_7.3.6=true

default.pref_update_mobile=true

default.pref_invert=true

default.pref_subtitle=true

default.pref_night=true

default.pref_large=true

default.pref_default_zoom=true

default.acra.lastVersionNr=166

PHONE_MODEL=SM-G930F

BRAND=samsung

ANDROID_VERSION=8.0.0

PACKAGE_NAME=de.tap.easy_xkcd

LOGCAT=11-30 02:50:50.615 E/AndroidRuntime(21131): at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.view.View.updateDisplayListIfDirty(View.java:19277)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.view.View.updateDisplayListIfDirty(View.java:19277)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.view.View.updateDisplayListIfDirty(View.java:19277)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.view.View.updateDisplayListIfDirty(View.java:19277)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.view.View.updateDisplayListIfDirty(View.java:19277)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.view.View.updateDisplayListIfDirty(View.java:19277)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.view.View.updateDisplayListIfDirty(View.java:19277)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:800)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.view.ViewRootImpl.draw(ViewRootImpl.java:3496)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3283)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2818)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1780)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7827)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.view.Choreographer.doCallbacks(Choreographer.java:723)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.view.Choreographer.doFrame(Choreographer.java:658)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.os.Handler.handleCallback(Handler.java:789)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.os.Handler.dispatchMessage(Handler.java:98)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.os.Looper.loop(Looper.java:164)

11-30 02:50:50.615 E/AndroidRuntime(21131): at android.app.ActivityThread.main(ActivityThread.java:6944)

11-30 02:50:50.615 E/AndroidRuntime(21131): at java.lang.reflect.Method.invoke(Native Method)

11-30 02:50:50.615 E/AndroidRuntime(21131): at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)

11-30 02:50:50.615 E/AndroidRuntime(21131): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

11-30 02:50:50.616 E/ACRA    (21131): ACRA caught a RuntimeException for de.tap.easy_xkcd

11-30 02:50:50.616 E/ACRA    (21131): java.lang.RuntimeException: Canvas: trying to draw too large(134117388bytes) bitmap.

11-30 02:50:50.616 E/ACRA    (21131): at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97)

11-30 02:50:50.616 E/ACRA    (21131): at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)

11-30 02:50:50.616 E/ACRA    (21131): at android.widget.ImageView.onDraw(ImageView.java:1367)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.View.draw(View.java:20373)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.View.updateDisplayListIfDirty(View.java:19318)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.View.draw(View.java:20096)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.ViewGroup.drawChild(ViewGroup.java:4421)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.View.updateDisplayListIfDirty(View.java:19309)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.View.updateDisplayListIfDirty(View.java:19277)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.View.updateDisplayListIfDirty(View.java:19277)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.View.updateDisplayListIfDirty(View.java:19277)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.View.updateDisplayListIfDirty(View.java:19277)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.View.updateDisplayListIfDirty(View.java:19277)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.View.updateDisplayListIfDirty(View.java:19277)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.View.updateDisplayListIfDirty(View.java:19277)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.View.updateDisplayListIfDirty(View.java:19277)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.View.updateDisplayListIfDirty(View.java:19277)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.View.updateDisplayListIfDirty(View.java:19277)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:800)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.ViewRootImpl.draw(ViewRootImpl.java:3496)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3283)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2818)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1780)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7827)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.Choreographer.doCallbacks(Choreographer.java:723)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.Choreographer.doFrame(Choreographer.java:658)

11-30 02:50:50.616 E/ACRA    (21131): at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)

11-30 02:50:50.616 E/ACRA    (21131): at android.os.Handler.handleCallback(Handler.java:789)

11-30 02:50:50.616 E/ACRA    (21131): at android.os.Handler.dispatchMessage(Handler.java:98)

11-30 02:50:50.616 E/ACRA    (21131): at android.os.Looper.loop(Looper.java:164)

11-30 02:50:50.616 E/ACRA    (21131): at android.app.ActivityThread.main(ActivityThread.java:6944)

11-30 02:50:50.616 E/ACRA    (21131): at java.lang.reflect.Method.invoke(Native Method)

11-30 02:50:50.616 E/ACRA    (21131): at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)

11-30 02:50:50.616 E/ACRA    (21131): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

USER_COMMENT=cant open newest comic

**Comment by tom-anders** [comment]
Hey, sorry this took me so long to fix. As of release 7.3.11 this should never happen again for any past or future comics.

**Comment by sophie-kuehn** [comment]
Looks fine now. Thanks for taking care :-)
