### ISSUE TITLE
App crashes when clicking "Donate"  button.

### ISSUE THREAD

**Issue by YYYSSSHHH** [tom-anders/Easy_xkcd#267]
**Environment Info：**
APK Version: 7.3.9 (166)
Android simulator version: 6.0.1

**Repro Steps：**

Revoke storage permission of app in the background.
1.Click the _Favorite_ button.
2.Click the _Donate_ button and then the app will crash.
![crash](https://user-images.githubusercontent.com/55122523/125017845-8118a100-e0a6-11eb-8118-f9bbcf191241.png)

Do you confirm this bug? Thank you.

**Comment by YYYSSSHHH** [comment]
Do you judge this as a defect?

**Comment by tom-anders** [comment]
Yeah definitely (sorry for taking so Long to respond)

Does it really only crash when you press the Favorite Button beforehand?

**Comment by YYYSSSHHH** [comment]
> Yeah definitely (sorry for taking so Long to respond)
> 
> Does it really only crash when you press the Favorite Button beforehand?

I tried a few more times . It may have nothing to do with the Favorite Button. Just click the "donate" button and it will crash

**Comment by tom-anders** [comment]
Fixed in the beta (also in the main branch, but not released yet)
