### ISSUE TITLE
Zooming sometimes flips the comic

### ISSUE THREAD

**Issue by Haspamelodica** [tom-anders/Easy_xkcd#275]
#### Description
When zooming in and out via the "double-tap then drag" gesture (is there a name for this?) the comic sometimes flips upside down.
I first noticed this with comic 1942 "Memorable Quotes", but confirmed it on other comics as well.

A reliable way to trigger this bug seems to be to repeatedly zoom to the minimum and maximum size., but it rarely also occurs when using the gesture normally.

#### System information
Phone model: ZTE Blade A5 2020
Android version: 9.0
EasyXKCD version: 7.3.11

#### Screenrecord
https://youtu.be/q_MoHhMHoJs
(as YouTube link because the video hits GitHub's upload size restriction)

![Screenshot_20211025_071800](https://user-images.githubusercontent.com/46954095/138647987-fd2f4f7a-d48e-41e8-a35c-9a9786b27b53.jpg)

**Comment by tom-anders** [comment]
For future reference, this was a problem in the PhotoView lib fixed in version 2.3.0: https://github.com/Baseflow/PhotoView/pull/667
