### ISSUE TITLE
alt text margin too low

### ISSUE THREAD

**Issue by tennox** [tom-anders/Easy_xkcd#277]
App works great and has not much to wish for.

Only annoyance I have:
The alt text (when "always show" is enabled) has a very low margin - I have a display with curved corners (painted them in 😅 ) but also towards the FloatingActionButton:
![Screenshot_20211118-205515__01__01](https://user-images.githubusercontent.com/2084639/142487867-93b7a9ed-e58f-42e0-a4f9-eab9c63a52a0.jpg)

**Comment by tom-anders** [comment]
@tennox Will be included in the 8.0 release
