### ISSUE TITLE
Home screen widgets do not display

### ISSUE THREAD

**Issue by 190n** [tom-anders/Easy_xkcd#278]
When I try to add either widget (latest or random comic) to my home screen, the comic isn't shown. All that is drawn is what seems to be a small rounded semitransparent gray rectangle (circled):

<img src="https://user-images.githubusercontent.com/7763597/142961820-11442c1f-b5c1-4e4b-b006-8f04b9aa4d8c.jpg" alt="Adding the widget to the home screen" width="400"> <img src="https://user-images.githubusercontent.com/7763597/142961485-909d0d8b-6e9a-4a43-986a-6315fa6ee4c7.png" alt="Only a small pill is displayed" width="400">

Let me know if I should collect any more information to narrow this issue down. I'm running OxygenOS 11.1.1.1 (Android 11) on a OnePlus 6 with Lawnchair 2.0-2589 as my launcher. I have granted the launcher permission to draw widgets; I have other widgets from Authy and Termux which are displayed just fine.

**Comment by tom-anders** [comment]
Fixed in beta2
