### ISSUE TITLE
[Beta] Overview tab loads to bottom after first time

### ISSUE THREAD

**Issue by WeirdAlex03** [tom-anders/Easy_xkcd#286]
App version: 8.0-beta1
OS version: Android 9
Device: Motorola moto g⁶

I found that the Overview tab only loads to the correct place for the first time per app session. After that, it always loads to the very bottom (comic 1).

Whether I select a comic from the overview or just go to the Browser tab without selecting a comic, returning to the Overview tab will show my the very bottom of the list, not the comic I left off on.

Using the back button or otherwise restarting the app starts a new session which fixes this, but only the first time. Subsequently opening the Overview tab will show the bottom again. (Using the home button to close the does not trigger a new session and does not fix this, unless I wait so long that the process is killed in the background.)

**Comment by tom-anders** [comment]
Fixed in beta-2, thanks for the report!
