### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [tom-anders/Easy_xkcd#292]
billingclient is not foss so it's not allowed in F-Droid. Could you please add a flavor without billingclient for F-Droid? Thanks!

**Comment by tom-anders** [comment]
@linsui when I have created the flavor, how can I add it to the metadata file? I couldn't find a matching key in the documentation.

**Comment by linsui** [comment]
See https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/de.tap.easy_xkcd.yml#L1311. `yes` will just build with `gradle assembleRelease`. if a flavor is specified, e.g. `fdroid` then `gradle assembleFdroidRelease` will be executed.

**Comment by tom-anders** [comment]
Thanks, I opened a Merge Request: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10920

**Comment by linsui** [comment]
Thanks!
