### ISSUE TITLE
Unable to download most recent comic(s) after downloading articles/comics

### ISSUE THREAD

**Issue by intelati26** [tom-anders/Easy_xkcd#294]
One of my priorities for the app is to have an offline backup of the comics.

Unfortunately after the app revamp, I noticed the most recent comic wasn't downloading. I cleared data, and the comic was immediately downloaded as expected. I decided to redownload the comics that same day. Now, several days later, I have run into the same exact issue.

I have left the app open for minutes at a time with no change. I have cleared cache, with no change. I have attached a couple of screenshots showing the loading circle.

(Hmm.... the GitHub app is eating my screenshots?)![Weird. Here it is](https://user-images.githubusercontent.com/11883481/164571636-4474cb3f-8ae2-4f7f-ac0e-a1411329f3f8.png)

**Comment by tom-anders** [comment]
Hi, I fixed this in v8.0.4, are you still on an earlier version?
