### ISSUE TITLE
Directly browsing comics by number

### ISSUE THREAD

**Issue by SebiderSushi** [tom-anders/Easy_xkcd#295]
Prior to version 8.0 typing a number into the search box and hitting enter would directly navigate to the respective comic.

Is there another way to open a specific comic by number other than manually seeking to it using the scrollbar on the overview page?  
If not, is it an intended feature in version 8.0?

**Comment by tom-anders** [comment]
Ah that was an oversight, gonna add that back

**Comment by vineet131** [comment]
Hello, what's the status on this? It's really annoying when I want to search for a comic by number but it doesn't show up

**Comment by SebiderSushi** [comment]
Works as expected as of v8.3 (191)
