### ISSUE TITLE
Wrong settings screen is opened

### ISSUE THREAD

**Issue by mueller-ma** [tom-anders/Easy_xkcd#304]
When I open the settings and press "Advanced" the "offline mode & notifications" settings screen is opened.

I'm using the latest version on F-Droid, 8.0.4.

**Comment by FineFindus** [comment]
Hmm, I'm on version 8.2.1 and cannot replicate this. Maybe this has been fixed and can be closed?

**Comment by tom-anders** [comment]
Agreed, this should've been fixed via 15acc5971337544f61c7acc87b39f431faab4bdd
