### ISSUE TITLE
"Meta-Alternating Current" (2642) loading never completes

### ISSUE THREAD

**Issue by gsax** [tom-anders/Easy_xkcd#309]
Version 8.1.1 from F-Droid
In the comic list, comic "Meta-Alternating Current" (2642) shows the green spinner without ever loading.
Comic can be "opened", showing the same spinner.
Long press shows the Alt Text.
Same symptons as issue #186

**Comment by gsax** [comment]
It now works.
It suddenly started to load the image today.
Where was no update from the F-Droid version.
So I don't know why or what is the reason for this.

**Comment by tom-anders** [comment]
This was probably an API issue. Also looks good on my device now, so let's close this issue.
