### ISSUE TITLE
New interface has shuffle button covering comics

### ISSUE THREAD

**Issue by happysmash27** [tom-anders/Easy_xkcd#311]
I just updated Easy XKCD today, and the new interface doesn't work very well. The shuffle button, rather than being entirely within the bottom bar, now covers comics when it didn't before, which gets in the way and is very annoying. Could some method please be added to push the random button into the bottom bar, or to push comics up such that they are not covered by the button?

**Comment by tom-anders** [comment]
I increased the bottom margin a bit so that the button won't overlap the comic (when image is not zoomed)

Might take a few days for the update to show up for you, Google Play is still checking some data protection questionnares I had to fill out...

**Comment by tom-anders** [comment]
![image](https://user-images.githubusercontent.com/13141438/213934729-d622ea35-7239-42b8-aed4-97d1aea43c8c.png)
