### ISSUE TITLE
Invert colored images toggle backward

### ISSUE THREAD

**Issue by isomeme** [tom-anders/Easy_xkcd#334]
In night mode on two different Android devices, the night mode toggle to control whether images with color are inverted seems to work backward. When it's toggled on, colored images are not inverted; when it's toggled off, colored images are inverted.

Note that the toggle for black and white images works as expected.

**Comment by tom-anders** [comment]
@FineFindus do you want to take a look?

**Comment by tom-anders** [comment]
Thank you very much, @FineFindus!
