### ISSUE TITLE
Export & import favorites

### ISSUE THREAD

**Issue by gustav-langer** [tom-anders/Easy_xkcd#347]
It would be nice if it was possible to export your favorite comics and what ifs into a file and also to import again from such a file for backups or moving to a different device.

I haven't looked into other xkcd viewer apps so I'm not aware of file formats already in use, but since this is basically just a list of numbers, many formats could be possible.

**Comment by tom-anders** [comment]
That's already possible! When in the favorites tab, you can select "Favorites Export/Import" from the menu, that will export them to a file :)
