### ISSUE TITLE
Should only "switch comic when zoomed in" when initiating new swipe

### ISSUE THREAD

**Issue by jimbo1qaz** [tom-anders/Easy_xkcd#64]
Right now, I can be zoomed into the comic, then swipe to pan around.

If my pan extends beyond the end of the comic, the app will automatically switch comics. That's generally not what I want.

It should first stop at the edge of the comic, then only switch comics if I swipe again in that direction.

Probably lots of corner cases...

**Comment by T-Rex96** [comment]
It's really difficult to implement. If you find an open source app that behaves they way you described, I can take look at it though

**Comment by jimbo1qaz** [comment]
Well, even the AOSP 4.4 gallery switches pictures when zoomed in... :(

**Comment by T-Rex96** [comment]
On the other hand, the latest Google Photos App does not (at least on my device)
