### ISSUE TITLE
Allow External SD Card for Offline Storage

### ISSUE THREAD

**Issue by KennyStier61** [tom-anders/Easy_xkcd#73]
When trying to choose my SD card as the offline storage location by going up a directory from the default view, it says operation not permitted.

**Comment by T-Rex96** [comment]
I think this is an issue with the directory chooser library I'm using. I set Environment.getExternalStorageDirectory() as the default view, since it _should_ give you the path of the external sd card, but that  doesn't seem to work for some manufacturers. I'll try finding a different library..

**Comment by T-Rex96** [comment]
In this version the default view is set to the root directory of the file system, can you see if it works for you?

https://www.dropbox.com/s/z1ty0tca02rqjzq/5.0.5.apk?dl=0

**Comment by 19kestier** [comment]
Nope, still the same result.
https://up1.ca/#Fc-vCRCRmuodGRyJHWWsHw

**Comment by T-Rex96** [comment]
Oh, wrong apk actually, what about this one?

https://www.dropbox.com/s/z1ty0tca02rqjzq/5.0.5.apk?dl=0
