### ISSUE TITLE
Use cached icon when no internet connection available

### ISSUE THREAD

**Issue by rugk** [tom-anders/Easy_xkcd#99]
When e.g. the widget updates and later I go into flight mode so no internet connection is available and I tap on the widget it cannot load the current image even through it is already displayed in the widget.

What's worse is that once I did this also the widgets is cleared and only shows a transparent widget now.

**Comment by T-Rex96** [comment]
I'll see if I can fix this.. In the meantime, have you considered enabling offline mode?

**Comment by rugk** [comment]
I did enabled offline mode/flight mode/however you want to call it. That's all what caused this issue, so I don't understand the question.

**Comment by T-Rex96** [comment]
I was talking about _the app's_ offline mode, which downloads all comics to our phone ;)

**Comment by rugk** [comment]
Ah, yes all right. No I currently don't want to use it. Maybe I could use it if it downloads only newer pictures (and ignores the old xkcd pictures).
